// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortenerAPI.Data;

namespace URLShortenerAPI.Migrations
{
    [DbContext(typeof(UrlInfoContext))]
    [Migration("20190604062923_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("URLShortenerAPI.Models.UrlInfo", b =>
                {
                    b.Property<int>("UrlInfoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("LongUrl")
                        .IsRequired();

                    b.Property<string>("ShortUrl");

                    b.Property<string>("Suffix");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("UrlInfoId");

                    b.ToTable("UrlInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
